export default [
    {
        id: 1,
        title: "San Francisco",
        location: "USA",
        googleMapsUrl: "https://goo.gl/maps/j9raWYXQXJ9HAAJY8",
        startDate: "9 Aug 2022",
        endDate: "10 Aug 2022",
        description: "The first city I've visited in USA is San Francisco. It's a lovely city that worth for visiting. First time staying in a backpacker hostel, Armsterdam Hostel and love it! For the first time feel so touched looking at the Golden Gate Bridge. It's just feel like I'm finally 'here'. Get to see a beautiful sunset and the night view at there. I came back again on the 30 Aug to complete my bucket list - walk on the Golden Gate Bridge.",
        img: "../images/golden-gate-bridge.JPEG",
    },
    {
        id: 2,
        title: "Lake Tahoe",
        location: "USA",
        googleMapsUrl: "https://goo.gl/maps/bjPrw6MNhvKKfbJZ7",
        startDate: "22 Aug 2022",
        endDate: "24 Aug 2022",
        description: "Lake Tahoe is a freshwater lake in the Sierra Nevada of the Western United States, straddling the border between California and Nevada and it is largest alpine lake in North America. It's my first 'nature' kind of places that I've visited in USA and the view is really breathtaking. Stay in a wooden cabin like the one in Switzerland. First time trying pladdleboards and swimming in Lake Tahoe. Get to do double kayak.",
        img: "../images/lake-tahoe.JPEG",
    },
    {
        id: 3,
        title: "RV Road Trip in AZ & UT",
        location: "USA",
        googleMapsUrl: "https://goo.gl/maps/hghn3GStmygZuvkd9",
        startDate: "19 Sep 2022",
        endDate: "27 Sep 2022",
        description: "First time driving a RV. Visited 5 national parks and a few scenic spots included Grand Canyon National Park, Antelope Canyon, Horseshoe Bend, Capitol Reef National Park, Arches National Park, Canyonlands National Park, Bryce Canyon National Park, Zion National Park. Enjoyed the scenic sunset view in Horseshoe Bend. Experienced the coldest sunrise (3°C) in Bryce Canyon National Park.",
        img: "../images/delicate-arch.JPEG",
    },
    {
        id: 4,
        title: "Solo Road Trip in VT & NH",
        location: "USA",
        googleMapsUrl: "https://goo.gl/maps/nFDn6fbcaouLAzoA6",
        startDate: "4 Oct 2022",
        endDate: "9 Oct 2022",
        description: "First time doing solo road trip by myself. Driving alone all the way from Boston to Vermont to meet with Bernice. Feel so amazed by the view along the journey. It's my very first fall failage. Travelled around Vermont with Bernice and Lisa, our host. She is so nice and showed us around Vermont. Continued the journey alone to New Hampshire. Get to see the most scenic view for this autumn.",
        img: "../images/stowe.jpeg",
    },
]